export const APP_NAME = 'Emphant Studio'

export const IPC_CHANNELS = {
  APP_INFO: 'app:get-info',
  WORKSPACE_SCAN: 'workspace:scan-files',
  WORKSPACE_READ_FILE: 'workspace:read-file',
  DOCUMENT_EXTRACT: 'document:extract',
  WORKSPACE_SELECT_DIRECTORY: 'workspace:select-directory',
  WORKSPACE_GET_DEFAULT_DIRECTORY: 'workspace:get-default-directory',
  WORKSPACE_LOAD_CONTENT: 'workspace:load-content',
  WORKSPACE_SAVE_CONTENT: 'workspace:save-content',
  KNOWLEDGE_SAVE_SOURCE: 'knowledge:save-source',
  KNOWLEDGE_READ_SOURCE: 'knowledge:read-source',
  KNOWLEDGE_INDEX_SOURCE: 'knowledge:index-source',
  KNOWLEDGE_START_EXTRACTION: 'knowledge:start-extraction',
  KNOWLEDGE_EXTRACTION_EVENT: 'knowledge:extraction-event',
  CLIPBOARD_WRITE_TEXT: 'clipboard:write-text',
  AGENT_RUN: 'agent:run',
  AGENT_APPROVE: 'agent:approve',
  AGENT_CANCEL: 'agent:cancel',
  AGENT_EVENT: 'agent:event',
  AGENT_GENERATE_TOPIC_TITLE: 'agent:generate-topic-title',
  MEMORY_GET_GREETING: 'memory:get-greeting',
  MEMORY_GET_PROFILE: 'memory:get-profile',
  MEMORY_UPDATE_PROFILE_FACT: 'memory:update-profile-fact',
  MEMORY_DELETE_PROFILE_FACT: 'memory:delete-profile-fact',
  MEMORY_UPDATE_PROFILE_RELATION: 'memory:update-profile-relation',
  MEMORY_DELETE_PROFILE_RELATION: 'memory:delete-profile-relation',
  MEMORY_UPDATE_AVATAR: 'memory:update-avatar',
  MEMORY_DELETE_AVATAR: 'memory:delete-avatar',
  EMAIL_CREDENTIAL_SET: 'email-credential:set',
  EMAIL_CREDENTIAL_DELETE: 'email-credential:delete',
  EMAIL_CHECK_ALL: 'email:check-all',
  EMAIL_SEND: 'email:send',
  CREDENTIAL_SET: 'credential:set',
  CREDENTIAL_DELETE: 'credential:delete',
  CREDENTIAL_STATUS: 'credential:status',
  PROVIDER_LIST_MODELS: 'provider:list-models',
  MCP_TEST_SERVER: 'mcp:test-server'
} as const
